### ISSUE TITLE
Can it be `namespace testUtils`?

### ISSUE THREAD

**Issue by saschanaz** [whatwg/testutils#8]
I doubt there's any requirement for `testUtils` be a class instance, so can we make it a namespace instead?

**Comment by jgraham** [comment]
@annevk is this reasonable? I'm not sure what the conventions/tradeoffs here are.

**Comment by annevk** [comment]
I'm not super familiar with IDL namespaces. @domenic?

(If this is the pattern I guess that means `navigator` should have been one too, but it's too late now?)

**Comment by saschanaz** [comment]
Navigator uses mixins but namespace currently doesn't have it, so that's not possible at least for now 👀 (Not sure there's other restrictions)

**Comment by domenic** [comment]
Yeah, I think the modern version would be to use a namespace (and rename to `TestUtils`, since namespaces are typically uppercased). This avoids the implication that it's an instance of a class, which doesn't really fit.

The caveat is that namespaces are kind of minimal right now, with the plan being to add any features to them that we need as we need them. So you might run into gaps in the future.

The upside is that the following code works with a namespace:

```js
const { gc } = TestUtils;
gc();
```

but the corresponding code does not work with an interface (since it'd be missing the `this` object, i.e. it only works if you call it as a method `testUtils.gc()` or `gc.call(testUtils)`).
